### ISSUE TITLE
How i can set villager type snow, desert, etc.

### ISSUE THREAD

**Issue by rymusov** [jacky8399/BalancedVillagerTrades#11]
remove-stone-trade:
  desc: Removes stone trades from masons
  enabled: true
  when:
    villager: profession = mason
    ingredient-0:
      matches:
        - type = stone
  do:
    remove: true
allow-stone-trade-snow:
  desc: Removes stone trades from masons
  enabled: false
  when:
    villager.profession: mason
    villager.type: snow
    ingredient-0:
      matches:
        - type = stone
  do:
    remove: true
    
    
Using this, but doesnt work, applyed for all villagers

**Comment by rymusov** [comment]
btw i didnt write villager.type: snow into do: section

**Comment by jacky8399** [comment]
Have you tried "remove: false" instead?
